tasks:
  install:
    image: node:carbon
    command:
      - npm
    args:
      - install
      - -g
      - nodemailer-cli
  test:
    image: node:carbon
    command:
      - nodemailer
    args:
      - test@test.com
      - test@test.com
      - $(env)
      - -j
      - "Sail env"
      - --server
      - debugmail.io
      - -r
      - 25
      - --nossl
